### ISSUE TITLE
Update docs with instructions on monitoring different machines with SigNoz

### ISSUE THREAD

**Issue by pranay01** [SigNoz/signoz.io-old#343] opened 2022-06-02 19:19 UTC
Context:
https://signoz-community.slack.com/archives/C01HWUTP4HH/p1654107684361919?thread_ts=1654077445.717789&cid=C01HWUTP4HH

**Comment by ankitnayan** [comment] 2022-06-14 06:58
Duplicate of https://github.com/SigNoz/signoz.io/issues/309

**Closed as completed by ankitnayan** 2022-06-14 06:58 UTC
Labels: documentation, metrics
